* Sampling Methods
** Basic Terminology
*** Raw Data
Term used for numbers and category labels that have not been processed yet.
*** Variable
A characteristic that can differ from one individual to another.
*** Observational Unit
A single individual who participated in the study. More simply, an individual may be called an observation.
*** Observation
May also be used to describe the value of a single measurement.
*** Sample Size
The total number of observational units.
*** Dataset
The complete set of raw data, for all observational units and variables in a survey or experiment.
*** Sample Data
Data that is taken from a subset of the population.
*** Population Data
    Data taken from the entire population.
*** Confounder
When 2 groups differ with respect to some factor other than the treatment *and* the factor affects the treatment, we say that the effect is confounded with the treatment.
** Types of Variables
*** Categorical
Categorical characteristics like gender. It can be called an ordinal variable when it has ordered categories, like rating one's skills from 1 to 5, with 5 being the most skillful.(nominal variable means non-ordinal, where there is no inherent order).
*** Numerical
**** Discrete
Discrete variables which are either measurements or counts taken on an individual. Examples are years of education, number of classes taken, etc.
**** Continuous
Used for numerical variables where every value within a range is a possible result. Examples are like height.
** Experiments
*** Experimental Studies
The ideal experiment should consist of entirely randomized controls, and is double-blind. Double-blindedness is important because the placebo effect is well-documented. Also, for example a doctor might be less likely to diagnose a patient positive for a disease if he knew that the patient has been vaccinated before.
*** Observational Studies
Sometimes it's not practical to conduct an experimental study. Example is smoking, because it is not ethical to get people to smoke just for the sake of the experiment. The results of an observational study indicate *association, not causation*.
** Sampling
Two types of sampling: probability sampling and non-probability sampling.
*** Probability Sampling
Involve planned use of chance. Normally more difficult to implement, but eliminates subjectivity and is more likely to give us a representative sample.
**** Simple-random
Draw each sample unit at random. Each unit has an equal chance of being sampled. Any subset of k individuals have the same chance of being sampled as any other subset of k individuals. It is the gold-standard, but often hard/costly to implement.
**** Systematic
Ordered list, starting with a number and then sample all individuals of a particular interval. Need to ensure that the ordered list does not conceal any pattern that might affect the outcome.
**** Cluster
Divide population into subgroups that are representative of the population. Randomly select clusters, and then sample every individual in that cluster. Example: dengue prevention inspection.
**** Stratified
Like quota sampling but makes use of chance instead of judgment. Split population into mutually-exclusive groups and then use simple random sampling. 
*** Non-probability Sampling
Often more convenient to obtain, but need to be mindful of the pitfalls.
**** Quota
Split population into mutually-exclusive groups and sample them proportionally. Important to be careful of the variables and conditions of splitting.
**** Convenience
Example: Getting students in a lecture to raise up their hands. Not representative of population.
**** Judgment
Make your own judgment of what is an appropriate sample. For example, stand outside a canteen and sample people who pass by. Judgment might introduce bias, even when done by an expert.

* Making Sense of Data
There are two steps in making sense of data:
** Graphical Display of Distributions
*** Categorical Variables
**** Pie Charts
Area (and angle) of each slice corresponds to the percentage of each outcome.
Pie charts are a very bad way of reperenting information. The eye is much better judging linear measures rather than relative areas. Bar charts or pareto charts are much better.
**** Bar Charts
- Length of each bar indicates frequency.
- Fixed width.
- Horizontal or vertical.
- To draw attention to relative proportions, can replace count with percentage frequency.
**** Pareto Charts
- Vertical bar chart plotted in descending order.
- Cumulative line graph on the same diagram.
- Can use different axes for bar and line graph (label carefully!).
- Using common axis alows for both count and percentage to be displayed in one slide.
- Quickly identifies the major components and their cumulative share.

*** Quantitative Variables
**** Histograms
- Split the range of data into intervals called bins.
- Count the number of observations of each bin.
- Plot either counts or relative frequencies of each bin.
**** Stem-and-leaf Plots
- Contains two plots separated by a vertical line.
- Left column is stem and right is column.
- These are especially useful when you make them by hand for batches of fewer than a few hundred values.
- Quick way to display and even record numbers.

5|6\\
6|0444\\
6|8888\\
7|2222\\
7|6666\\
8|000044\\
8|8\\

Stem-and-leaf plots help to find even more data from numerical aspects rather than the shape. Notice that these are all even numbers. Perhaps it could be because heartbeats are taken for 15 seconds and multiplied by 4, rather than recorded for the whole duration of 60 seconds?
**** Dotplots
- Dots are plotted on a scale.
- A dot for each observation.
- Visual summary of information when data is not too large.
- May not be able to identify patterns if data is too small.
- Useful to find unusual features.

** Numerical Measures (summary/descriptive statistics)
Two types of descriptive/summary statistics:
*** Measures of Location
Statistics that consider where the data are centered.
**** Mean
The average. Its limitation is that it is oversensitive to extreme values. In which case, it may not be a representative of the location of the majority of sample points.
**** Median
The midpoint. If even number of data, then take the average of the middle two. Its advantage is that it is insensitive to extreme values. However, it is determined mainly by middle points and is less sensitive to the actual numeric points of the remaining data points.
**** Mode
Measure of the most frequent data point. Note: Some distributions have more than one mode. In fact, a useful form of classifying distributions is the number of modes present. Unimodal, bimodal, and trimodal, etc.

The key drawback is that it is ineffective when there are a large number of points, each of which occur infrequently. In such cases, mode will occur far off the center or in extreme cases, will not exist.

If all data points appear once or the same number of times, it is said that *there is no mode*.
*** Measures of Scale or Spread
Statistics that describe variability. For example, variance, range, IQR.
**** Range
Difference between the maximum and minimum data point. It is easy to compute, but ignores all information between the two extremes. It is also very sensitive to extreme values. Another disadvantage is that it depends on the sample size. The larger the size, the bigger the range tends to be. This complication makes it difficult to compare the ranges of sets of differing size.
**** Quantiles and Percentiles
The *pth percentile* is a value where p percent of values fall below that value. The 50th percentile is the median. The more specific definition of the pth percentile is as such:
1. The (k+1)th largest sample point if np/100 is not an integer (where k is the largest integer less than np/100, and n is the sample size);
2. The average of the (np/100)th and the ((np/100)+1)th largest observations if np/100 is an integer.

Percentiles are also known quantiles. The three most useful percentiles are the quartiles. First quartile has p = 25; second quartile is p = 50; and third quartile is where p = 75.

**** Sample Variance (Standard Deviation)
One good way to measure spread is to be:

\begin{equation}
d = \frac{1}{n} \sum\limits_{i=1}^n (x_i - \bar{x})
\end{equation}

The problem with this is that the sum of all deviations about the mean will always be zero. To mitigate this, square it.

\begin{equation}
s^2 = \frac{1}{n-1} \sum\limits_{i=1}^n (x_i - \bar{x})^2
\end{equation}

The *sample standard deviation*, s, is the positive square root of the sample variance. The computational formula for s^2 is an efficient way to compute it:

\begin{equation}
s ^2 = \frac{1}{n-1} \left[\sum\limits_{i=1}^n x_i^2 - \frac{(\sum\limits_{i=1}^n x_i)^2}{n} \right]
\end{equation}
\begin{equation}
s^2 = \frac{1}{n-1} \left[\sum\limits_{i=1}^n x_i^2 - n \bar{x}^2 \right]
\end{equation}

Note that the *sample* variance is not really the variance of the sample. It is just a tool to estimate the *population* variance. It is the mean square distance to the population mean. But we don't usually have the population mean so we use the sample mean instead.

**** IQR (Inter-quartile Range)
Quartiles are also used to define a measure of spread that is more resistant to outliers compared to range and standard deviation.
IQR is the difference between Q3 and Q1. It is not affected by any measurements below Q1 and above Q3

**** Coefficient of Variation

This is a relative measure of variation. It is express as a percentage and is hence useable across differences in precision. For example, using kilograms in a cooking recipe is meaningless. The equation is:

\begin{equation}
CV = 100\% \times \frac{s}{|\bar{x}|}
\end{equation}
**** Boxplots
Also know as a box-and-whisker diagram, it depicts groups of numerical data through their five-number summaries: minimum, maximum, Q1, Q2 (median), and Q3. Note that the min and max exclude outliers, which are data points that are either lower than 1.5 x IQR below Q1, or higher than 1.5 x IQR above Q3.

Boxplots are usually plotted together with stem-and-leaf or histograms. Boxplots offer a balance of simplicity and information. They are often plotted side-by-side for groups or categories we wish to compare.
* Tutorials
** Tutorial 1
*** 1
**** a
Population data.
**** b
Sample data.
*** 2
**** a
| Statistical Population                 | Sample                | Variable of Interest |
|----------------------------------------+-----------------------+----------------------|
| Engineers graduating from a university | 20 graduating seniors | Starting salary      |


**** b
| Statistical Population  | Sample   | Variable of Interest     |
|-------------------------+----------+--------------------------|
| 6000 manufactured chips | 50 chips | Whether defective or not |

**** c
| Statistical Population                           | Sample                            | Variable of Interest |
|--------------------------------------------------+-----------------------------------+----------------------|
| All specimens that can be made with the material | 20 specimens made of the material | Tensile strength     |

*** 3
**** a
Discrete because set number of hours (assuming no decimals).
**** b
Continuous because any value between range is possible.
**** c
Categorical. Only a few colours.
**** d
Categorical. Yes or No.
**** e
Categorical-ordinal.
*** 4
No. Convenience sampling. May introduce biases like selecting only people who pass by Platypus Food Bar at S16. (By right answer is "self-selected sampling". This is when investigators just leave the form there for everyone to participate if they want. The problem with this is that those who tend to participate tend to have strong opinions.)
*** 5
**** a
Randomized experiment.
**** b
Observational study.
**** c
Randomized experiment.
**** d
Observational study.
*** 6
**** a
Yes. Affects both parties. Number of modules affects amount of sleep and grades.
**** b
Not confounder. Weight doesnt affect grades nor sleep directly.
**** c
Not confounder. Partying affects sleep, but not necessarily grades.
Ans: Spend energy partying might have less energy studying.
*** 7
**** a
Convenience sampling. (Ans: Not convenience because for convenience sampling, convenience is for the respondents not the investigator. Self-select or volunteer sampling.)
**** b
No. Biased towards people who have strong opinion who are willing to take the time to respond to the poll.
